### ISSUE TITLE
NotImplementedError: Don't know how to literal-quote value datetime.datetime

### ISSUE THREAD

**Issue by grutz** [bbelyeu/Flask-SQLAlchemy-Caching#2]
Using Python 3.6 and latest SQLAlchemy (1.2.14), core.py fails when attempting to generate a string value for a query with a datetime value.

https://github.com/bbelyeu/Flask-SQLAlchemy-Caching/blob/master/flask_sqlalchemy_caching/core.py#L132 is the line at fault.

```
flask_1          | Traceback (most recent call last):
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
flask_1          |     return self.wsgi_app(environ, start_response)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/werkzeug/contrib/fixers.py", line 152, in __call__
flask_1          |     return self.app(environ, start_response)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
flask_1          |     response = self.handle_exception(e)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
flask_1          |     reraise(exc_type, exc_value, tb)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
flask_1          |     raise value
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
flask_1          |     response = self.full_dispatch_request()
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
flask_1          |     rv = self.handle_user_exception(e)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
flask_1          |     reraise(exc_type, exc_value, tb)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
flask_1          |     raise value
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
flask_1          |     rv = self.dispatch_request()
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
flask_1          |     return view_func(**req.view_args)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/flask_user/decorators.py", line 58, in decorator
flask_1          |     return view_function(*args, **kwargs)
flask_1          |   File "/flaskv1/app/controllers.py", line 458, in dashboard
flask_1          |     online_count = query.filter(Devices.last_check_in >= active_datetime).options(FromCache(cache)).count()
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3230, in count
flask_1          |     return self.from_self(col).scalar()
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 2983, in scalar
flask_1          |     ret = self.one()
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 2954, in one
flask_1          |     ret = self.one_or_none()
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 2924, in one_or_none
flask_1          |     ret = list(self)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/flask_sqlalchemy_caching/core.py", line 50, in __iter__
flask_1          |     return iter(self.get_value(createfunc=create_func))
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/flask_sqlalchemy_caching/core.py", line 90, in get_value
flask_1          |     cache, cache_key = self._get_cache_plus_key()
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/flask_sqlalchemy_caching/core.py", line 56, in _get_cache_plus_key
flask_1          |     return self._cache.cache, self._get_key()
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/flask_sqlalchemy_caching/core.py", line 62, in _get_key
flask_1          |     key = self.key_from_query()
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/flask_sqlalchemy_caching/core.py", line 132, in key_from_query
flask_1          |     key = str(stmt.compile(compile_kwargs={'literal_binds': True}))
flask_1          |   File "<string>", line 1, in <lambda>
flask_1          |
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 442, in compile
flask_1          |     return self._compiler(dialect, bind=bind, **kw)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 448, in _compiler
flask_1          |     return dialect.statement_compiler(dialect, self, **kw)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 453, in __init__
flask_1          |     Compiled.__init__(self, dialect, statement, **kwargs)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 219, in __init__
flask_1          |     self.string = self.process(self.statement, **compile_kwargs)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 245, in process
flask_1          |     return obj._compiler_dispatch(self, **kwargs)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/annotation.py", line 80, in _compiler_dispatch
flask_1          |     self, visitor, **kw)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
flask_1          |     return meth(self, **kw)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 1821, in visit_select
flask_1          |     text, select, inner_columns, froms, byfrom, kwargs)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 1900, in _compose_select_body
flask_1          |     for f in froms])
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 1900, in <listcomp>
flask_1          |     for f in froms])
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
flask_1          |     return meth(self, **kw)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 1462, in visit_alias
flask_1          |     asfrom=True, **kwargs) + \
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/annotation.py", line 80, in _compiler_dispatch
flask_1          |     self, visitor, **kw)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
flask_1          |     return meth(self, **kw)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 1821, in visit_select
flask_1          |     text, select, inner_columns, froms, byfrom, kwargs)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 1905, in _compose_select_body
flask_1          |     t = select._whereclause._compiler_dispatch(self, **kwargs)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
flask_1          |     return meth(self, **kw)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 829, in visit_clauselist
flask_1          |     for c in clauselist.clauses)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 826, in <genexpr>
flask_1          |     s for s in
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 829, in <genexpr>
flask_1          |     for c in clauselist.clauses)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
flask_1          |     return meth(self, **kw)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 1078, in visit_binary
flask_1          |     return self._generate_generic_binary(binary, opstring, **kw)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 1111, in _generate_generic_binary
flask_1          |     self, eager_grouping=eager_grouping, **kw)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
flask_1          |     return meth(self, **kw)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 1242, in visit_bindparam
flask_1          |     bindparam, within_columns_clause=True, **kwargs)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 1275, in render_literal_bindparam
flask_1          |     return self.render_literal_value(value, bindparam.type)
flask_1          |   File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/compiler.py", line 1293, in render_literal_value
flask_1          |     "Don't know how to literal-quote value %r" % value)
flask_1          | NotImplementedError: Don't know how to literal-quote value datetime.datetime(2018, 11, 18, 2, 10, 37, 78083)```

**Comment by bbelyeu** [comment]
Interesting. Just read this thread https://stackoverflow.com/questions/5631078/sqlalchemy-print-the-actual-query and it mentions that compile only has support for basic types.

It looks like you can create a custom type class for the datetime and a function "def process_literal_param" on that class and it should then work.

In our code we use a custom type from `from sqlalchemy_utils.types.arrow import ArrowType` and the https://arrow.readthedocs.io/en/latest/ for easier datetime manipulations. We haven't had any problems with that so it must implement the `process_literal_param` for us.

**Comment by bbelyeu** [comment]
Closing and recommending usage of Arrow as a custom type

**Comment by deepamgupta** [comment]
Convert `datetime` object to `str` in the `filter` clause worked for me.
Reference: https://stackoverflow.com/a/68402314/10204932

**Comment by deepamgupta** [comment]
Convert `datetime` object to `str` in the `filter` clause.
This worked for me.
Reference: https://stackoverflow.com/a/68402314/10204932

**Comment by mrsuh** [comment]
I had the same problem with the `DateTime` type. This error occurs if you want to compile your statement with only `literal_binds: True` argument and you have complex (not `int` or `string`) fields in query.
```python
stmt.compile(dialect=postgresql.dialect(), compile_kwargs={"literal_binds": True})
```
Solved it as [bbelyeu](https://github.com/bbelyeu) said with [TypeDecorator](https://docs.sqlalchemy.org/en/14/faq/sqlexpressions.html#rendering-bound-parameters-inline).
Solution:
```python
from sqlalchemy import insert, create_engine, MetaData, Table, Column, DateTime, TypeDecorator
from sqlalchemy.dialects import postgresql
import psycopg2
from datetime import datetime

engine = create_engine('postgresql+psycopg2://postgres:password@127.0.0.1/postgres')
conn = engine.connect()

class MyDateTimeType(TypeDecorator):
    impl = DateTime

    def process_literal_param(self, value, dialect):
        return value.strftime("'%Y-%m-%d %H:%M:%S'")

meta = MetaData()
dates = Table('dates', meta, Column('created_at', MyDateTimeType(), nullable=False))

stmt = (
    insert(dates).
    values(created_at=datetime.now())
)

raw_sql = stmt.compile(dialect=postgresql.dialect(), compile_kwargs={"literal_binds": True})

conn.execute(raw_sql)
```

**Comment by deepamgupta** [comment]
Dhanyawaad 🙏

**Comment by mike-usa** [comment]
```python
sa.literal_column(f'{datetime.now(timezone.utc)}')
```
---

I've encountered a similar issue in a flask_migrate (alembic) migration, which required me performing a data migration.  When changing a foreign-key column from nullable to non-nullable, you have to populate nulls with something, so I wanted to insert a record in the FK table to something like "SYSTEM" and use that (then cleanup later). 

There may be a better way, but in the migration file I had:

```python
users = sa.table('users', 
  sa.Column('id', sa.Integer),
  sa.Column('username', sa.String),
  sa.Column('created', sa.DateTime)
)
conn = op.get_bind()
sys_id = conn.execute(users.select().where(users.c.username=='SYSTEM'))
    
if not sys_id:
   sys_id = conn.execute(
      insert(users)
         .returning(users.c.id)
         .values(
            username='SYSTEM',
            created=datetime.now(timezone.utc)
         )
         .on_conflict_do_nothing()
```

This worked in practice, but using the `--sql` presenter, it encountered an error:
```
ERROR [flask_migrate] Error: Don't know how to literal-quote value datetime.datetime(2022, 1, 11, 12, 00, 00, 425185, tzinfo=datetime.timezone.utc)
```

**Comment by mike-usa** [comment]
One solution may be `sqlalchemy.literal_column`:
```python
sa.literal_column(f'{datetime.now(timezone.utc)}')
```
---

## Background

I've encountered a similar issue in a flask_migrate (alembic) migration, which I decided to include a data migration.  This was necessary as the business rules changed; a column with a foreign key reference was nullable and became non-nullable -- those existing nulls have to be populated with something. I wanted to insert a record in the FK table to use something like "SYSTEM" that I could cleanup after the migration processed. 

There may be a better way, but in the migration file I had:

```python
users = sa.table('users', 
  sa.Column('id', sa.Integer),
  sa.Column('username', sa.String),
  sa.Column('created_at', sa.DateTime)
)
conn = op.get_bind()
sys_id = conn.execute(users.select().where(users.c.username=='SYSTEM'))
    
if not sys_id:
   sys_id = conn.execute(
      insert(users)
         .returning(users.c.id)
         .values(
            username='SYSTEM',
            created_at=datetime.now(timezone.utc)
         )
         .on_conflict_do_nothing()
   )

if sys_id is not None:
  sys_id = sys_id.scalar()
```

This worked in practice when the migration ran, but using the `--sql` presenter encountered the error:
```
ERROR [flask_migrate] Error: Don't know how to literal-quote value datetime.datetime(2022, 1, 11, 12, 00, 00, 425185, tzinfo=datetime.timezone.utc)
```

## Solution

Similar to @deepamgupta's [suggestion](https://github.com/bbelyeu/Flask-SQLAlchemy-Caching/issues/2#issuecomment-925745815) to use a string, I passed a string to SQLAlchemy's `literal_column` method and it seems to have worked at least for the presentation (haven't tried executing yet).
```python
      insert(users)
         .returning(users.c.id)
         .values(
            username='SYSTEM',
            created_at=sa.literal_column(f'{datetime.now(timezone.utc)}')   #<-- here
         )
         .on_conflict_do_nothing()
```

---

Disclaimer: I'm still learning Python and still reading through the documentation to see the effects / side-effects. I welcome any teaching/coaching/knowledge-sharing around this subject.
